# Generated by Django 3.2.6 on 2021-09-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='date_debut',
            field=models.DateField(default='None'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_fin',
            field=models.DateField(default='None'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='mission',
            name='lieu',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='mission',
            name='état',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='absance',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='entre',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='retard',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='sortie',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='heurs_base',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='heurs_sup',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='primes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
