# Generated by Django 3.2.6 on 2021-09-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210901_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='date',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
